-- Farmers, Fishers, and Miners can build roads

INSERT INTO "Route_ValidBuildUnits"
	(	"RouteType",				"UnitType"				)
VALUES
	(	'ROUTE_ANCIENT_ROAD',		'UNIT_RURCOM_FARMER'	),
	(	'ROUTE_MEDIEVAL_ROAD',		'UNIT_RURCOM_FARMER'	),
	(	'ROUTE_INDUSTRIAL_ROAD',	'UNIT_RURCOM_FARMER'	),
	(	'ROUTE_MODERN_ROAD',		'UNIT_RURCOM_FARMER'	),
	(	'ROUTE_ANCIENT_ROAD',		'UNIT_RURCOM_FISHER'	),
	(	'ROUTE_MEDIEVAL_ROAD',		'UNIT_RURCOM_FISHER'	),
	(	'ROUTE_INDUSTRIAL_ROAD',	'UNIT_RURCOM_FISHER'	),
	(	'ROUTE_MODERN_ROAD',		'UNIT_RURCOM_FISHER'	),
	(	'ROUTE_ANCIENT_ROAD',		'UNIT_RURCOM_MINER'		),
	(	'ROUTE_MEDIEVAL_ROAD',		'UNIT_RURCOM_MINER'		),
	(	'ROUTE_INDUSTRIAL_ROAD',	'UNIT_RURCOM_MINER'		),
	(	'ROUTE_MODERN_ROAD',		'UNIT_RURCOM_MINER'		);

