-- Builders and Roman Legions can build roads

INSERT INTO "Route_ValidBuildUnits"
	(	"RouteType",				"UnitType"			)
VALUES
	(	'ROUTE_ANCIENT_ROAD',		'UNIT_BUILDER'		),
	(	'ROUTE_MEDIEVAL_ROAD',		'UNIT_BUILDER'		),
	(	'ROUTE_INDUSTRIAL_ROAD',	'UNIT_BUILDER'		),
	(	'ROUTE_MODERN_ROAD',		'UNIT_BUILDER'		),
	(	'ROUTE_ANCIENT_ROAD',		'UNIT_ROMAN_LEGION'	),
	(	'ROUTE_MEDIEVAL_ROAD',		'UNIT_ROMAN_LEGION'	),
	(	'ROUTE_INDUSTRIAL_ROAD',	'UNIT_ROMAN_LEGION'	),
	(	'ROUTE_MODERN_ROAD',		'UNIT_ROMAN_LEGION'	);
